### ISSUE TITLE
[CHECKLIST] Add (16, 2) and integrate 16-2 join/split tx

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-cosmwasm#23]
# Overview 

- [x] [TASK] add (16, 2) to match statement in `contracts/vanchor/src/contract.rs`
- [x] [TASK] Add 2 verifiers to the contract (small / large)
- [x] [TASK] Generate trusted parameters for 16-2 join/split:
        - [ ] 2 vanchor bridge
        - [ ] 8 vanchor bridge
- [x] [TASK] Add params to protocol-substrate-fixtures and include them in `contracts/vanchor/`
- [x] [TASK] Add integration tests

# Relevant Links

- Solidity implementation for [`vanchor_16`](https://github.com/webb-tools/protocol-solidity/tree/main/contracts/verifiers/vanchor_16) 
- Solidity implementation [`VAnchorVerifier.sol`](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/verifiers/VAnchorVerifier.sol#L11)
- Solidity implementation [`_executeVerification`](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/vanchors/VAnchor.sol#L288)

### Interfaces

- [`IVAnchorVerifier.sol`](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/interfaces/IVAnchorVerifier.sol)

### Tests

- Solidity vanchor tests targeting [`16_2`](https://github.com/webb-tools/protocol-solidity/blob/main/test/vanchor/vanchor.test.ts)
- Solidity vanchor bridge tests [`signatureVBridge.test.ts`](https://github.com/webb-tools/protocol-solidity/blob/main/test/vbridge/signatureVBridge.test.ts)
